# Enhanced version of docker-compose.yml with monitoring and log rotation
# Use this file with: docker compose -f docker-compose.yml -f docker-compose.enhanced.yml up

services:
  # Frontend service with enhanced logging
  frontend:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=frontend"
    volumes:
      - frontend-logs:/var/log/spheroseg/frontend

  # Backend service with enhanced logging
  backend:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=backend"
    volumes:
      - backend-logs:/var/log/spheroseg/backend

  # ML Service with enhanced logging
  ml-service:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=ml"
    volumes:
      - ml-logs:/var/log/spheroseg/ml

  # Prometheus with enhanced configuration
  prometheus:
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/prometheus/alerts.yml:/etc/prometheus/alerts.yml
      - prometheus-data:/prometheus
      - prometheus-logs:/var/log/spheroseg/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--alertmanager.url=http://alertmanager:9093'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=prometheus"  # Grafana with enhanced configuration and alerting
  grafana:
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./docker/grafana/alerting:/etc/grafana/provisioning/alerting
      - grafana-logs:/var/log/spheroseg/grafana
    environment:
      - GF_ALERTING_ENABLED=true
      - GF_UNIFIED_ALERTING_ENABLED=true
      - GF_ALERTING_EXECUTE_ALERTS=true
      - GF_LOG_LEVEL=info
      - GF_LOG_MODE=file
      - GF_PATHS_LOGS=/var/log/spheroseg/grafana
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=grafana"

  # Alertmanager for handling alerts
  alertmanager:
    image: prom/alertmanager:latest
    container_name: spheroseg-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./docker/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager-data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
    networks:
      - spheroseg-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=alertmanager"

volumes:
  frontend-logs:
    driver: local
  backend-logs:
    driver: local
  ml-logs:
    driver: local
  prometheus-logs:
    driver: local
  prometheus-data:
    driver: local
  grafana-logs:
    driver: local
  grafana-data:
    driver: local
  alertmanager-data:
    driver: local