services:
  # Test database
  test-database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: spheroseg_test
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off

  # Test Redis
  test-redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    tmpfs:
      - /data
    command: redis-server --save ""

  # Backend test service
  test-backend:
    build:
      context: .
      dockerfile: docker/backend.test.Dockerfile
    environment:
      NODE_ENV: test
      DATABASE_URL: postgresql://testuser:testpass@test-database:5432/spheroseg_test
      REDIS_URL: redis://test-redis:6379
      JWT_ACCESS_SECRET: test-jwt-access-secret-for-testing-only
      JWT_REFRESH_SECRET: test-jwt-refresh-secret-for-testing-only
      EMAIL_SERVICE: mock
      EMAIL_FROM: test@spheroseg.local
      EMAIL_TIMEOUT: 1000
      SKIP_EMAIL_SEND: true
      LOG_LEVEL: error
      DISABLE_RATE_LIMITING: true
      ENABLE_TEST_ROUTES: true
    ports:
      - "3002:3001"
    depends_on:
      - test-database
      - test-redis
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
      - ./backend/jest.config.js:/app/jest.config.js
      - ./backend/jest.setup.js:/app/jest.setup.js
      - ./backend/jest.integration.config.js:/app/jest.integration.config.js
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/package.json:/app/package.json
      - ./backend/uploads/test:/app/uploads
      - /app/node_modules
    command: ["sleep", "infinity"]  # Keep container running for tests

  # ML service test
  test-ml:
    build:
      context: .
      dockerfile: docker/ml.test.Dockerfile
    environment:
      ENVIRONMENT: test
      LOG_LEVEL: ERROR
      MODEL_PATH: /tmp/test_models
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    ports:
      - "8001:8000"
    volumes:
      - ./backend/segmentation:/app
      - ./backend/segmentation/tests:/app/tests
      - /tmp/test_models:/tmp/test_models
    command: ["sleep", "infinity"]  # Keep container running for tests

  # Frontend test service
  test-frontend:
    build:
      context: .
      dockerfile: docker/frontend.test.Dockerfile
    environment:
      NODE_ENV: test
      VITE_API_URL: http://test-backend:3001/api
      VITE_ML_SERVICE_URL: http://test-ml:8000
      VITE_WS_URL: ws://test-backend:3001
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./vite.config.ts:/app/vite.config.ts
      - ./vitest.config.ts:/app/vitest.config.ts
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./postcss.config.js:/app/postcss.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
      - ./package.json:/app/package.json
      - ./playwright.config.ts:/app/playwright.config.ts
      - /app/node_modules
    command: ["sleep", "infinity"]  # Keep container running for tests

networks:
  default:
    name: spheroseg-test