services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: spheroseg-db
    network_mode: "host"
    environment:
      - POSTGRES_USER=spheroseg
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=spheroseg_prod
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
      - PGPORT=5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/db-backup:/backup
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U spheroseg -d spheroseg_prod"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: spheroseg-redis
    network_mode: "host"
    command: redis-server --port 6379 --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ML Service
  ml:
    build:
      context: ./backend/segmentation
      dockerfile: ../../docker/ml.prod.Dockerfile
    container_name: spheroseg-ml
    network_mode: "host"
    volumes:
      - ./backend/segmentation/weights:/app/weights:ro
      - ml-cache:/app/cache
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - WORKERS=2
      - MAX_REQUESTS=100
      - TIMEOUT=300
      - LOG_LEVEL=info
      - PORT=8000
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.production.Dockerfile
    container_name: spheroseg-backend
    network_mode: "host"
    env_file: .env.production
    volumes:
      - ./backend/uploads:/app/uploads
      - backend-logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - DATABASE_URL=postgresql://spheroseg:${DB_PASSWORD}@localhost:5432/spheroseg_prod?sslmode=disable
      - REDIS_URL=redis://localhost:6379
      - ALLOWED_ORIGINS=https://spherosegapp.utia.cas.cz
      - WS_ALLOWED_ORIGINS=https://spherosegapp.utia.cas.cz
      - SEGMENTATION_SERVICE_URL=http://localhost:8000
      - UPLOAD_DIR=/app/uploads
      - STORAGE_TYPE=local
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - RATE_LIMIT_ENABLED=true
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX=100
      - LOG_LEVEL=info
      - ENABLE_METRICS=true
    depends_on:
      - db
      - redis
      - ml
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend - just copies files to volume
  frontend:
    build:
      context: .
      dockerfile: docker/frontend-copy.Dockerfile
      args:
        - VITE_API_BASE_URL=https://spherosegapp.utia.cas.cz/api
        - VITE_ML_SERVICE_URL=https://spherosegapp.utia.cas.cz/api/ml
    container_name: spheroseg-frontend
    volumes:
      - frontend-static:/app/dist
    restart: always

  # Nginx Reverse Proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: spheroseg-nginx
    network_mode: "host"
    volumes:
      - ./docker/nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/sites:/etc/nginx/sites-enabled:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - nginx-cache:/var/cache/nginx
      - frontend-static:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  frontend-static:
    driver: local
  backend-logs:
    driver: local
  ml-cache:
    driver: local
  nginx-cache:
    driver: local