# GPU Override for Green Environment
services:
  green-ml:
    # Modern GPU configuration for Docker Compose
    device_requests:
      - driver: nvidia
        count: 1
        capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
