/**
 * GENERATED by `scripts/specimen-previews/generate.py` — do not hand-edit.
 *
 * One entry per preview tile shown on hover in the project-type and model
 * pickers. Each is a real production frame with the outlines the named model
 * actually produced; the geometry is fetched on hover from `geometry`, never
 * bundled, because the full set is ~200 kB of path data.
 *
 * `model` is the id, not a display name: the picker reads the name out of
 * MODEL_REGISTRY so a rename cannot leave a stale copy here.
 */

import type { ModelType } from '@/lib/models/modelRegistry';
import type { ProjectType } from '@/types';

export interface SpecimenPreview {
  /** Stable id; also the asset basename. */
  readonly id: string;
  readonly model: ModelType;
  readonly projectType: ProjectType;
  /** Tile under /public, 512 px square. */
  readonly image: string;
  /** Outline geometry under /public, fetched on hover. */
  readonly geometry: string;
  /** Outlines in the tile — the caption quotes it. */
  readonly objects: number;
}

export const SPECIMEN_PREVIEWS: readonly SpecimenPreview[] = [
  {
    id: 'hrnet-1',
    model: 'hrnet',
    projectType: 'spheroid',
    image: '/specimens/previews/hrnet-1.webp',
    geometry: '/specimens/previews/hrnet-1.geom.json',
    objects: 1,
  },
  {
    id: 'hrnet-2',
    model: 'hrnet',
    projectType: 'spheroid',
    image: '/specimens/previews/hrnet-2.webp',
    geometry: '/specimens/previews/hrnet-2.geom.json',
    objects: 1,
  },
  {
    id: 'hrnet-3',
    model: 'hrnet',
    projectType: 'spheroid',
    image: '/specimens/previews/hrnet-3.webp',
    geometry: '/specimens/previews/hrnet-3.geom.json',
    objects: 1,
  },
  {
    id: 'cbam_resunet-1',
    model: 'cbam_resunet',
    projectType: 'spheroid',
    image: '/specimens/previews/cbam_resunet-1.webp',
    geometry: '/specimens/previews/cbam_resunet-1.geom.json',
    objects: 2,
  },
  {
    id: 'cbam_resunet-2',
    model: 'cbam_resunet',
    projectType: 'spheroid',
    image: '/specimens/previews/cbam_resunet-2.webp',
    geometry: '/specimens/previews/cbam_resunet-2.geom.json',
    objects: 1,
  },
  {
    id: 'cbam_resunet-3',
    model: 'cbam_resunet',
    projectType: 'spheroid',
    image: '/specimens/previews/cbam_resunet-3.webp',
    geometry: '/specimens/previews/cbam_resunet-3.geom.json',
    objects: 2,
  },
  {
    id: 'unet_spherohq-1',
    model: 'unet_spherohq',
    projectType: 'spheroid',
    image: '/specimens/previews/unet_spherohq-1.webp',
    geometry: '/specimens/previews/unet_spherohq-1.geom.json',
    objects: 1,
  },
  {
    id: 'unet_spherohq-2',
    model: 'unet_spherohq',
    projectType: 'spheroid',
    image: '/specimens/previews/unet_spherohq-2.webp',
    geometry: '/specimens/previews/unet_spherohq-2.geom.json',
    objects: 1,
  },
  {
    id: 'unet_spherohq-3',
    model: 'unet_spherohq',
    projectType: 'spheroid',
    image: '/specimens/previews/unet_spherohq-3.webp',
    geometry: '/specimens/previews/unet_spherohq-3.geom.json',
    objects: 1,
  },
  {
    id: 'segformer-1',
    model: 'segformer',
    projectType: 'spheroid',
    image: '/specimens/previews/segformer-1.webp',
    geometry: '/specimens/previews/segformer-1.geom.json',
    objects: 1,
  },
  {
    id: 'segformer-2',
    model: 'segformer',
    projectType: 'spheroid',
    image: '/specimens/previews/segformer-2.webp',
    geometry: '/specimens/previews/segformer-2.geom.json',
    objects: 1,
  },
  {
    id: 'segformer-3',
    model: 'segformer',
    projectType: 'spheroid',
    image: '/specimens/previews/segformer-3.webp',
    geometry: '/specimens/previews/segformer-3.geom.json',
    objects: 3,
  },
  {
    id: 'mamba_unet-1',
    model: 'mamba_unet',
    projectType: 'spheroid',
    image: '/specimens/previews/mamba_unet-1.webp',
    geometry: '/specimens/previews/mamba_unet-1.geom.json',
    objects: 1,
  },
  {
    id: 'mamba_unet-2',
    model: 'mamba_unet',
    projectType: 'spheroid',
    image: '/specimens/previews/mamba_unet-2.webp',
    geometry: '/specimens/previews/mamba_unet-2.geom.json',
    objects: 5,
  },
  {
    id: 'mamba_unet-3',
    model: 'mamba_unet',
    projectType: 'spheroid',
    image: '/specimens/previews/mamba_unet-3.webp',
    geometry: '/specimens/previews/mamba_unet-3.geom.json',
    objects: 2,
  },
  {
    id: 'spheroid_disintegration-1',
    model: 'spheroid_disintegration',
    projectType: 'spheroid_invasive',
    image: '/specimens/previews/spheroid_disintegration-1.webp',
    geometry: '/specimens/previews/spheroid_disintegration-1.geom.json',
    objects: 170,
  },
  {
    id: 'spheroid_disintegration-2',
    model: 'spheroid_disintegration',
    projectType: 'spheroid_invasive',
    image: '/specimens/previews/spheroid_disintegration-2.webp',
    geometry: '/specimens/previews/spheroid_disintegration-2.geom.json',
    objects: 114,
  },
  {
    id: 'spheroid_disintegration-3',
    model: 'spheroid_disintegration',
    projectType: 'spheroid_invasive',
    image: '/specimens/previews/spheroid_disintegration-3.webp',
    geometry: '/specimens/previews/spheroid_disintegration-3.geom.json',
    objects: 123,
  },
  {
    id: 'wound-1',
    model: 'wound',
    projectType: 'wound',
    image: '/specimens/previews/wound-1.webp',
    geometry: '/specimens/previews/wound-1.geom.json',
    objects: 3,
  },
  {
    id: 'wound-2',
    model: 'wound',
    projectType: 'wound',
    image: '/specimens/previews/wound-2.webp',
    geometry: '/specimens/previews/wound-2.geom.json',
    objects: 4,
  },
  {
    id: 'wound-3',
    model: 'wound',
    projectType: 'wound',
    image: '/specimens/previews/wound-3.webp',
    geometry: '/specimens/previews/wound-3.geom.json',
    objects: 3,
  },
  {
    id: 'sperm-1',
    model: 'sperm',
    projectType: 'sperm',
    image: '/specimens/previews/sperm-1.webp',
    geometry: '/specimens/previews/sperm-1.geom.json',
    objects: 19,
  },
  {
    id: 'sperm-2',
    model: 'sperm',
    projectType: 'sperm',
    image: '/specimens/previews/sperm-2.webp',
    geometry: '/specimens/previews/sperm-2.geom.json',
    objects: 10,
  },
  {
    id: 'sperm-3',
    model: 'sperm',
    projectType: 'sperm',
    image: '/specimens/previews/sperm-3.webp',
    geometry: '/specimens/previews/sperm-3.geom.json',
    objects: 11,
  },
  {
    id: 'microtubule-1',
    model: 'microtubule',
    projectType: 'microtubules',
    image: '/specimens/previews/microtubule-1.webp',
    geometry: '/specimens/previews/microtubule-1.geom.json',
    objects: 54,
  },
  {
    id: 'microtubule-2',
    model: 'microtubule',
    projectType: 'microtubules',
    image: '/specimens/previews/microtubule-2.webp',
    geometry: '/specimens/previews/microtubule-2.geom.json',
    objects: 82,
  },
  {
    id: 'microtubule-3',
    model: 'microtubule',
    projectType: 'microtubules',
    image: '/specimens/previews/microtubule-3.webp',
    geometry: '/specimens/previews/microtubule-3.geom.json',
    objects: 26,
  },
  {
    id: 'microcapsule-1',
    model: 'microcapsule',
    projectType: 'microcapsule',
    image: '/specimens/previews/microcapsule-1.webp',
    geometry: '/specimens/previews/microcapsule-1.geom.json',
    objects: 11,
  },
  {
    id: 'microcapsule-2',
    model: 'microcapsule',
    projectType: 'microcapsule',
    image: '/specimens/previews/microcapsule-2.webp',
    geometry: '/specimens/previews/microcapsule-2.geom.json',
    objects: 8,
  },
  {
    id: 'microcapsule-3',
    model: 'microcapsule',
    projectType: 'microcapsule',
    image: '/specimens/previews/microcapsule-3.webp',
    geometry: '/specimens/previews/microcapsule-3.geom.json',
    objects: 8,
  },
  {
    id: 'neurite_soma-1',
    model: 'neurite_soma',
    projectType: 'neurite',
    image: '/specimens/previews/neurite_soma-1.webp',
    geometry: '/specimens/previews/neurite_soma-1.geom.json',
    objects: 16,
  },
  {
    id: 'neurite_soma-2',
    model: 'neurite_soma',
    projectType: 'neurite',
    image: '/specimens/previews/neurite_soma-2.webp',
    geometry: '/specimens/previews/neurite_soma-2.geom.json',
    objects: 19,
  },
  {
    id: 'neurite_soma-3',
    model: 'neurite_soma',
    projectType: 'neurite',
    image: '/specimens/previews/neurite_soma-3.webp',
    geometry: '/specimens/previews/neurite_soma-3.geom.json',
    objects: 31,
  },
] as const;
